# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_aiservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto_aiservice.proto\"\x1f\n\x0ePredictRequest\x12\r\n\x05image\x18\x01 \x01(\t\"!\n\x0fPredictResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"D\n\rReportRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x10\n\x08\x63pu_load\x18\x02 \x01(\t\x12\x10\n\x08mem_load\x18\x03 \x01(\t\" \n\x0eReportResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2;\n\tAiService\x12.\n\x07Predict\x12\x0f.PredictRequest\x1a\x10.PredictResponse\"\x00\x32:\n\x0bGateService\x12+\n\x06Report\x12\x0e.ReportRequest\x1a\x0f.ReportResponse\"\x00\x42\x0eZ\x0cpb/aiserviceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_aiservice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\014pb/aiservice'
  _PREDICTREQUEST._serialized_start=25
  _PREDICTREQUEST._serialized_end=56
  _PREDICTRESPONSE._serialized_start=58
  _PREDICTRESPONSE._serialized_end=91
  _REPORTREQUEST._serialized_start=93
  _REPORTREQUEST._serialized_end=161
  _REPORTRESPONSE._serialized_start=163
  _REPORTRESPONSE._serialized_end=195
  _AISERVICE._serialized_start=197
  _AISERVICE._serialized_end=256
  _GATESERVICE._serialized_start=258
  _GATESERVICE._serialized_end=316
# @@protoc_insertion_point(module_scope)
